name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:
jobs:
  test-ios-app:
    if: github.event.pull_request.draft == false
    runs-on:
      - self-hosted
      - macOS
      - ARM64
      - kmm24-fun
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        run: xcodes select
      - name: Pre-build Script
        run: sh ./ci_scripts/ci_pre_xcodebuild.sh
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Setup Project
        run: make install
      - name: Setup Firebase
        run: echo "${{ secrets.GOOGLE_SERVICES_INFO_PLIST }}" > ./DoLater/GoogleService-Info.plist
      - name: Test
        run: make test
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}
